name: Deploy Core Internal Module to EC2

on:
  pull_request:
    branches: [main]
    paths:
      - internal/**
      - common/**
      - domain/**
      - .github/workflows/deploy-internal.yml

env:
  app-name: myce-internal
  app-port: 8082
  deploy-host: internal

jobs:
  build-internal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v5.0.0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build internal module with gradle
        run: ../gradlew clean build -x test
        working-directory: internal

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push api module Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./internal/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.app-name }}:latest

      - name: Trigger deploy ansible
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh api -X POST /repos/MYCE-Refactoring/myce-infra/dispatches \
            -f event_type='deploy-myce-core' \
            -f client_payload[service]=${{ env.app-name }} \
            -f client_payload[port]=${{ env.app-port }} \
            -f client_payload[deploy-host]=${{ env.deploy-host }}